### ISSUE TITLE
Chrome Autofill: the label is not floated

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1742] opened 2019-01-18 11:59 UTC
### What Angular MDC version are you using?
0.43.3

### What browser(s) is this bug affecting?
Chrome  71.0.3578.98, maybe more browsers

------------------------------------------
![image](https://user-images.githubusercontent.com/16443111/51385493-1d8e0800-1b28-11e9-8230-fddae6450bbe.png)

**Comment by ofekashery** [comment] 2019-01-18 11:59
Re #410

**Comment by ofekashery** [comment] 2019-01-23 18:49
I'm really not sure, it only happens once in a while

**Comment by ofekashery** [comment] 2019-01-23 18:53
Code:
```HTML
<mdc-text-field outlined class="mt-2" label="{{ 'pages.account.subpages.login.password' | translate }}" [(ngModel)]="password" type="password" required></mdc-text-field>
```

Maybe it's because of the translation? We use [``@ngx-translate/core``](https://github.com/ngx-translate/core).

**Comment by ofekashery** [comment] 2019-02-26 14:04
@trimox try to look at this: https://github.com/material-components/material-components-web/issues/4447#issuecomment-467214641

**Comment by trimox** [comment] 2019-02-26 15:52
@ofekashery Thanks for the heads up. Taking a look.

**Comment by trimox** [comment] 2019-04-19 16:51
Duplicate of https://github.com/trimox/angular-mdc-web/issues/1813

**Closed by trimox** 2019-04-19 16:51 UTC
Labels: bug
