### ISSUE TITLE
MDC List active item

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#380] opened 2017-11-14 16:11 UTC
Hi, 

I would like to know how to set active item in the mdc-list based on router url.

Thx

**Comment by Eski** [comment] 2017-11-14 16:14
I forgot to mention that I'm talking about **mdc-list** in **mdc-permanent-drawer**.
How can i set the **mdc-permanent-drawer-selected** based on router.

**Comment by trimox** [comment] 2017-11-15 10:44
@Eski Setting actively selected item feature is in [v0.6.1 milestone](https://github.com/trimox/angular-mdc-web/milestone/9) (Nov 20th or earlier).
Closing as it's a duplicate of #143.

**Closed by trimox** 2017-11-15 10:44 UTC
