### ISSUE TITLE
Select: Menu flickers before disappearing.

### ISSUE THREAD

**Issue by henev** [trimox/angular-mdc-web#509] opened 2018-01-08 06:25 UTC
### What Angular MDC version are you using?
0.6.6

### What browser(s) is this bug affecting?
Chrome - latest

### What OS are you using?
Ubuntu 16.04

### What are the steps to reproduce the bug?
1. Go to demo page -> Inputs -> Select
1. Open select menu of first example
1. Choose an option

### What is the expected behavior?
Menu should close smoothly without flickering.

### What is the actual behavior?
Menu flickers and moves before disappearing. The animations should copy [the official example of the MDC](https://material-components-web.appspot.com/select.html).

**Comment by trimox** [comment] 2018-01-09 00:52
Nice catch. Working on a fix.

**Comment by trimox** [comment] 2018-01-10 11:47
@henev Good news. Closing animation is working correctly using `material-components-web` v0.28.0.

Leaving issue open until our update to `material-components-web` v0.28.0 is completed.

**Comment by trimox** [comment] 2018-01-19 12:09
Closing. Angular MDC v0.7.0 will be published today, and resolves this.

**Comment by trimox** [comment] 2018-02-03 19:59
Sorry, thought issue was resolved with 0.7.0 release. I found the root cause, PR incoming.

**Closed** 2018-02-03 20:13 UTC
